---
# tasks file for lighthouse-role
  - name: Install dependencies lighthouse
    ansible.builtin.yum: 
        name: git
        state: present

  - name: Copy from git lighthouse
    become: true
    git:
      repo: "{{ lighthouse_vcs }}"
      version: master
      dest: "{{ lighthouse_location_dir }}"
  - name: Create lighthouse config
    become: true
    template:
      src: "template/lighthouse.conf.j2"
      dest: "/etc/nginx/conf.d/default.conf"
      mode: 0644
    notify: reload-nginx